version: '3'

services:
  lb:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - ./lb.conf:/etc/nginx/nginx.conf

  app1:
    image: kennethreitz/httpbin

  app2:
    image: kennethreitz/httpbin

