version: '3'

services:
  lb:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - ./lb.conf:/etc/nginx/nginx.conf

  app1:
    image: nginx
    volumes:
    - ./app1.conf:/etc/nginx/nginx.conf

  app2:
    image: nginx
    volumes:
    - ./app2.conf:/etc/nginx/nginx.conf
