apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: kustomize-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: api
