---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-app
  namespace: gotk-system
spec:
  interval: 1m0s
  path: ./kustomize-controller/deploy/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-app
  validation: client

